---
- name: manage_lvm | manage physical volume group creation
  include_tasks: create_vg.yml

- name: manage_lvm | loop over logical volume group(s) to create logical volumes
  include_tasks: create_lv.yml
  loop: "{{ lvm_groups }}"
  loop_control:
    loop_var: vg

- name: manage_lvm | loop over logical volume group(s) to create filesystems
  include_tasks: create_fs.yml
  loop: "{{ lvm_groups }}"
  loop_control:
    loop_var: vg

- name: manage_lvm | Removing LVM logical volume(s)
  lvol:
    vg: "{{ item.0.vgname }}"
    lv: "{{ item.1.lvname }}"
    state: "absent"
    force: yes
  become: true
  loop: "{{ lvm_groups|subelements('lvnames') }}"
  when: >
    (item.1 is defined and
    item.1 != 'None') and
    (item.1.create is defined and
    not item.1.create)

- name: manage_lvm | Removing LVM volume group(s)
  lvg:
    vg: "{{ item.vgname }}"
    pvs: "{{ item.disks | join(',') }}"
    state: "absent"
  become: true
  loop: "{{ lvm_groups }}"
  when: >
    item.create is defined and
    not item.create
