---
- name: Configure RHEL7 Operating System.
  hosts: test
  become: yes
  #connection: local
  gather_facts: yes

  roles:
    - users

  vars:
    pkgs:
      - httpd
      - python3
      - python3-pip
      - perl
      - strace
      
  tasks:
  - name: Install pre-requisite packages
    yum: name={{ pkgs }} state=installed

  - yum_repository:
      name: docker-repo
      description: repo for Docker
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
      enabled: yes
      gpgcheck: no
    
  - yum_repository:
      name: centos-Extra
      description: repo for centos Extra Packages
      baseurl: http://mirror.centos.org/centos/7/extras/x86_64/
      enabled: yes
      gpgcheck: no
    when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")

  - yum_repository:
      name: oracle-client
      description: repo for centos Extra Packages
      baseurl: http://yum.oracle.com/​repo/​OracleLinux/​OL7/​oracle/​instantclient/​x86_64
      enabled: yes
      gpgcheck: no

  - name: containerd.io
    yum:
      name: containerd.io
      state: present
      update_cache: true
    when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")

  - name: docker-ce
    yum:
      name: docker-ce
      state: present
      update_cache: true
    when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")

  - name: docker-ce-cli
    yum:
      name: docker-ce-cli
      state: present
      update_cache: true
    when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")

  - name: Start and enable the Docker daemon
    service: name=docker state=started enabled=yes
    when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")

  - name: python3-pip
    yum:
      name: python3-pip
      state: present
      update_cache: true

  - name: oracle-client-19.1
    yum:
      name: oracle-instantclient19.10-basic-19.10.0.0.0
      state: present
      update_cache: true

- name: Download perlbrew install.sh
    become: yes
    get_url:
      url: https://install.perlbrew.pl
      dest: /opt/install.perlbrew.pl
      mode: 0755

- name: Run a script with arguments (using 'cmd' parameter)
  ansible.builtin.script:
    cmd: /opt/install.perlbrew.pl

- name: Modify bashrc for user
  lineinfile:
    dest: ~/.bashrc
    backup: yes
    line: "fi;\nsource ~/perl5/perlbrew/etc/bashrc\n"
    regexp: ''
    state: present
    insertafter: EOF
    create: True