---
- name: Configure RHEL7 Operating System.
  hosts: test
  become: yes
  #connection: local
  gather_facts: yes

  roles:
    - users

  vars:
    pkgs:
      - httpd
      - python3
      - python3-pip
      - perl
      - strace
      
  tasks:
  - name: Install pre-requisite packages
    yum: name={{ pkgs }} state=installed

  - yum_repository:
      name: docker-repo
      description: repo for Docker
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
      enabled: yes
      gpgcheck: no
    
  - yum_repository:
      name: centos-Extra
      description: repo for centos Extra Packages
      baseurl: http://mirror.centos.org/centos/7/extras/x86_64/
      enabled: yes
      gpgcheck: no
      when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")

  # - yum_repository:
  #     name: docker-rhel7-repo
  #     description: repo for Docker
  #     baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
  #     enabled: no
  #     gpgcheck: no

  # - yum_repository:
  #     name: docker-rhle-repo
  #     description: repo for Docker
  #     baseurl: https://download.docker.com/linux/rhel/
  #     enabled: yes
  #     gpgcheck: no

  - name: docker-ce
    yum:
      name: docker-ce
      state: present
      update_cache: true
      when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")

  - name: Start and enable the Docker daemon
      service: name=docker state=started enabled=yes

  - name: python3-pip
    yum:
      name: python3-pip
      state: present
      update_cache: true

  # - name: Installing docker sdk
  #   command: pip3 install docker

  # - name: Install Docker
  #     yum: name=docker state=latest

  # - name: Docker repo
  #   get_url:
  #   url: https://download.docker.com/linux/rhel/docker-ce.repo
  #   dest: /etc/yum.repos.d/docker-ce.repo

  # - name: python3
  #   yum:
  #     name: python3
  #     state: present
  #   update_cache: true

  # - name: python3-pip
  #   yum:
  #     name: python3-pip
  #     state: present
  #   update_cache: true

  # - name: Install Docker
  #     yum: name=docker state=latest
