---
- name: Configure Debian 10 Operating System.
  hosts: test
  become: yes
  connection: local
  gather_facts: yes

  roles:
    - users

  vars:
    pkgs:
      - apache2
      - python3
      - python3-pip
      - docker.io
      - perl
      - aptitude 
      - curl
      - bzip2 
      - patch 
      - build-essential 
      - unzip
      
  tasks:
  - name: Install pre-requisite packages
    apt: name={{ pkgs }} state=installed

  - name: Start and enable the Docker daemon
    service: name=docker state=started enabled=yes

  - name: export python3 site-package path
    command: "echo 'export PATH='python3 -m site --user-base/bin:$PATH'' >> ~/.bashrc source ~/.bashrc"

  - name: pip3 install virtualenv
    pip:
      name: "virtualenv"
      executable: pip3

  - name: create virtualenv
    pip:
      name: "boto3"
      virtualenv: "~/venv"
      #virtualenv_command: "{{ virtualenv_command | default(omit) }}"
      virtualenv_python: python3
      virtualenv_site_packages: yes

  - name: install virtualenv packages
    pip:
      name: "{{ item.name | default(item, true) }}"
      version: "{{ item.version | default(omit, true) }}"
      state: "{{ item.state | default('present', true) }}"
      virtualenv: "~/venv"
    with_items: "{{ virtualenv_pre_packages }}"

  - name: Copy OracleClient directory to the remote server
    copy:
      src: ./files/
      dest: /var/tmp/
      mode: 0755

  - name: Run a script to install OracleInstantClient
    ansible.builtin.script: /var/tmp/instantclient-install.sh

  - name: Download perlbrew install.sh
    become: yes
    get_url:
      url: https://install.perlbrew.pl
      dest: /opt/install.perlbrew.pl
      mode: 0755

  - name: copy carton setup script
    copy:
      src: carton-setup.sh
      dest: /var/tmp/carton-setup.sh
      mode: 0755

  - name: Run a script to install perlbrew and carton
    ansible.builtin.script: /var/tmp/carton-setup.sh
