---
- name: Configure RHEL7 Operating System.
  hosts: test
  become: yes
  #connection: local
  gather_facts: yes

  roles:
    - users

  vars:
    pkgs:
      - httpd
      - python3
      - python3-pip
      - perl
      - strace
      
  tasks:
  - name: Install pre-requisite packages
    yum: name={{ pkgs }} state=installed

  - yum_repository:
    name: docker-repo
    description: repo for Docker
    baseurl: https://download.docker.com/linux/rhel/
    enabled: yes
    gpgcheck: no

  - name: Install docker-ce
    yum:
      name: docker-ce
      state: present
      update_cache: true

  - name: Start and enable the Docker daemon
    service: name=docker state=started enabled=yes

  - name: Installing docker sdk
    command: pip3 install docker



  # - name: Install Docker
  #     yum: name=docker state=latest

  # - name: Docker repo
  #   get_url:
  #   url: https://download.docker.com/linux/rhel/docker-ce.repo
  #   dest: /etc/yum.repos.d/docker-ce.repo

  # - name: python3
  #   yum:
  #     name: python3
  #     state: present
  #   update_cache: true

  # - name: python3-pip
  #   yum:
  #     name: python3-pip
  #     state: present
  #   update_cache: true
  
  # - name: Install Docker
  #     yum: name=docker state=latest
